sudo: false
language: php
php:
  - 5.4

script:
  - git clone https://github.com/eteubert/plugin-deployment-demo.git eteubert/plugin-deployment-demo
  - cd eteubert/plugin-deployment-demo
  - git checkout -qf $TRAVIS_COMMIT

deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy.sh
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ (pre|alpha|beta|rc)[0-9]+$"
